SET(IMAGO_VERSION "2.0.0")

IF($ENV{BUILD_NUMBER})
   SET(IMAGO_BUILD_VERSION $ENV{BUILD_NUMBER})
ELSE()
   SET(IMAGO_BUILD_VERSION 0)
ENDIF()

SET(IMAGO_VERSION_EXT "${IMAGO_VERSION}.${IMAGO_BUILD_VERSION} ${PACKAGE_SUFFIX}")
